package dev.dearrudam.simulator.domain.model;

/**
 * Domain model for a synthetic incident generated by the simulator.
 * No framework dependencies — pure domain object.
 */
public record SimulatedIncident(String title, String description, String domain) {
}
